@startuml Class Diagram

Database {
    class IMS {
        + checkStock()
        + shipOrder()
        + addBook()
    }

    Class User {
        + role: int
        + name: string
        + email: string
        + pref_library: int
    }

    class Employee {
        + name: string
    }

    class Customer {
        + address: string
        + placeOrder()
        + payOrder()
    }

    class Order {
        
        + invoiceId: int
        + checkStatus(): int
    }

    class Invoice {
        + checkPayment(): boolean
    }

    Class Transaction {
        + 
    }

    class Book {
        
        + name: string
        + getBook()
    }



}
