@startuml
left to right direction
skinparam actorstyle awesome

actor "Student" as Student
actor "Magazijnmedewerker" as Staff
actor "Schoolbeheerder" as School

package "Inventory Management Systeem" {
    
    
    package "Beveiligde Omgeving (Login Vereist)" #line.dashed {
        usecase "Producten Zoeken & Bestellen" as Order
        usecase "Retour Aanvragen" as Return
        usecase "Leerlijsten Beheren" as Booklist
        usecase "Bestellingen Verwerken" as Process
        usecase "Voorraad Muteren" as Inventory
        usecase "Innames Registreren" as Intake
    }
}


Student -- Order
Student -- Return

School -- Booklist

Staff -- Process
Staff -- Intake
Staff -- Inventory


note top of "Beveiligde Omgeving (Login Vereist)"
  Alle acties in dit blok hebben een beveiligde login vereist. 
  Alleen geautoriseerde gebruikers kunnen deze functies uitvoeren.
end note

@enduml
