@startuml
left to right direction
skinparam actorstyle awesome

actor "Gebruiker" as User
actor "Magazijn medewerker" as Staff
actor "School" as School

package "Inventory Management System" {
  
    usecase "Zoeken & Bestellen" as Order
    usecase "Leningen Beheren" as manageLoans
    usecase "Account Beheren" as Account
    usecase "Leerlijsten Beheren" as Booklist
    
    
    usecase "Voorraad Beheren" as Inventory
    usecase "Bestellingen Verwerken" as Process
    usecase "Inname & Retouren" as Returns
}


User --> Order
User --> manageLoans
User --> Account

School --> Booklist

Staff --> Inventory
Staff --> Process
Staff --> Returns


Returns <-- User : Retourneren
@enduml