@startuml
left to right direction
skinparam actorstyle awesome

actor "Gebruiker" as User
actor "Magazijn medewerker" as Staff
actor "School" as School

package "Inventory Management System" {
  
    usecase "Zoeken & Bestellen" as Order
    usecase "Leerlijsten Beheren" as Booklist
    
    
    usecase "Voorraad Beheren" as Inventory
    usecase "Bestellingen Verwerken" as Process
    usecase "Retouren" as Returns
    usecase "Innamen" as Intake



User --> Order

School --> Booklist

Staff --> Inventory
Staff --> Process
Staff --> Intake


Returns <-- User 
@enduml