@startuml usecase
left to right direction
skinparam actorstyle awesome

actor "Lener" as User
actor "Medewerker" as Staff

package "Library System" {
    usecase "Catalogus zoeken, Reserveren & Afhaalplek selecteren" as Reserve
    usecase "Leen geschiedenis beheren" as Account
    
    usecase "Inname & Uitgifte" as Loan
    usecase "Facturatie & Boetes" as Billing
    usecase "Transport" as Logistics
    usecase "Wachtlijsten beheer" as Waitlist
}

User -- Reserve
User -- Account

Staff -- Loan
Staff -- Billing
Staff -- Logistics
Staff -- Waitlist
@enduml