@startuml
title Inname
skinparam actorStyle awesome
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
skinparam titleBorderColor Grey
skinparam titleBackgroundColor Lavender

actor Medewerker
participant "Magazijn systeem" as Systeem
actor School


School -> Systeem : Submit boekenlijst
Systeem -> Medewerker : Melding over nieuwe boekenlijst
Medewerker -> Systeem : Controleer lijst voor nieuwe boeken
Systeem --> Medewerker : Huidige voorraad
Medewerker -> Medewerker : Bestel nieuwe boeken (inkoop)
Medewerker -> Systeem : Registreer nieuwe boeken (inname)
Systeem --> Medewerker : Boeken verwerkt
@enduml