@startuml
title Terugnames
skinparam actorStyle awesome
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 1
skinparam titleBorderColor Grey
skinparam titleBackgroundColor Lavender

actor Medewerker
participant "Magazijn Systeem" as System
actor Gebruiker

Gebruiker -> Medewerker : Stuur boeken retour
Medewerker -> System : Controleer retour
System -> Gebruiker : Stuur retour conformatie
Medewerker -> System : Update voorraad
@enduml